# Generated by Django 3.2.7 on 2021-09-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210915_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(verbose_name='review date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(choices=[('1', 'NOT MY CUP OF TEA!'), ('3', 'IT WAS GOOD!'), ('5', 'IT WAS AMAZING! I COULD NOT PUT IT DOWN!')], default='1', max_length=1),
        ),
    ]
